[package]
name = "heron"
version = "0.1.0"
edition = "2024"

[dependencies]
threadpool = "1.8.1"
termcolor = "1.4"
serde_ini = "0.2.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
llvm-sys = "211"

